version: '3.7'                      #version de docker-compose utilizada, en la pag esta la compatibilidad de cada version: https://docs.docker.com/compose/compose-file/compose-versioning/

services:
  ms_html_extraction:               #mombre del servicio, para el docker-compose
    container_name: ms_html_extraction
    build: ./CS_Evaluation/MS_HTML_extraction     #ubicación del archivo Docerfile para esta imagen 
    image: ms_html_extraction
    networks:
      - net_compatibily_service      #red en la cual se encuentran levantados los servicios 
    ports:
      - 8001:8001                   #puerto de de la maquina local(host) a traves del que se puede acceder al servicio levantado <puerto del host>:<puerto del servicio en el contenedor>
   
  ms_html_cleaning:
    container_name: ms_html_cleaning
    build: ./CS_Evaluation/MS_HTML_cleaning
    image: ms_html_cleaning
    networks:
      - net_compatibily_service
    ports:
      - 8002:8002

  #ms_a_evaluation:
    #container_name: ms_a_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_a_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8010:8010

  #ms_abbr_evaluation:
    #container_name: ms_abbr_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_abbr_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8011:8011

  ##ms_acronym_evaluation:
    #container_name: ms_acronym_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_acronym_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8012:8012

  #ms_applet_evaluation:
    #container_name: ms_applet_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_applet_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8013:8013

  #ms_area_evaluation:
    #container_name: ms_area_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_area_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8014:8014

  #ms_audio_evaluation:
    #container_name: ms_audio_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_audio_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8015:8015

  #ms_button_evaluation:
    #container_name: ms_button_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_button_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8016:8016

  #ms_dd_evaluation:
    #container_name: ms_dd_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_dd_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8018:8018

  #ms_div_evaluation:
    #container_name: ms_div_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_div_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8019:8019

  #ms_embed_evaluation:
    #container_name: ms_embed_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_embed_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8020:8020

  #ms_fieldset_evaluation:
    #container_name: ms_fieldset_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_fieldset_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8021:8021

  #ms_figure_evaluation:
    #container_name: ms_figure_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_figure_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8023:8023

  #ms_headings_evaluation:
    #container_name: ms_headings_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_headings_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8024:8024

  #ms_iframe_evaluation:
    #container_name: ms_iframe_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_iframe_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8025:8025

  ms_img_evaluation:
    container_name: ms_img_evaluation
    image: mss_evaluations
    entrypoint: python3 ./MS_img_evaluation/main.py
    networks:
      - net_compatibily_service
    ports:
      - 8026:8026

  #ms_input_evaluation:
    #container_name: ms_input_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_input_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8027:8027

  #ms_label_evaluation:
    #container_name: ms_label_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_label_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8028:8028

  #ms_legend_evaluation:
    #container_name: ms_legend_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_legend_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8029:8029

  #ms_link_evaluation:
    #container_name: ms_link_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_link_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8030:8030

  #ms_map_evaluation:
    #container_name: ms_map_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_map_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8031:8031

  #ms_object_evaluation:
    #container_name: ms_object_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_object_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8032:8032

  #ms_pre_evaluation:
    #container_name: ms_pre_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_pre_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8033:8033

  #ms_span_evaluation:
    #container_name: ms_span_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_span_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8034:8034

  #ms_table_evaluation:
    #container_name: ms_table_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_table_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8035:8035

  #ms_video_evaluation:
    #container_name: ms_video_evaluation
    #image: mss_evaluations
    #entrypoint: python3 ./MS_video_evaluation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 8036:8036

  evaluation_service:
    container_name: evaluation_service
    build: ./CS_Evaluation/Evaluation_Service
    image: evaluation_service
    networks:
      - net_compatibily_service
    ports:
      - 8000:8000
    links: 
      - ms_html_extraction
      - ms_html_cleaning
      #- ms_a_evaluation
      #- ms_abbr_evaluation
      #- ms_acronym_evaluation
      #- ms_applet_evaluation
      #- ms_area_evaluation
      #- ms_audio_evaluation
      #- ms_button_evaluation
      #- ms_dd_evaluation
      #- ms_div_evaluation
      #- ms_embed_evaluation
      #- ms_fieldset_evaluation
      #- ms_figure_evaluation
      #- ms_headings_evaluation
      #- ms_iframe_evaluation
      - ms_img_evaluation
      #- ms_input_evaluation
      #- ms_label_evaluation
      #- ms_legend_evaluation
      #- ms_link_evaluation
      #- ms_map_evaluation
      #- ms_object_evaluation
      #- ms_pre_evaluation
      #- ms_span_evaluation
      #- ms_table_evaluation
      #- ms_video_evaluation
      - recomendation_service
    environment:
      #- MS_A_EVALUATION=${MS_A_EVALUATION:-"ms_a_evaluation:8010/a_evaluation"}
      #- MS_ABBR_EVALUATION=${MS_ABBR_EVALUATION:-"ms_abbr_evaluation:8011/abbr_evaluation"}
      #- MS_ACRONYM_EVALUATION=${MS_ACRONYM_EVALUATION:-"ms_acronym_evaluation:8012/acronym_evaluation"}
      #- MS_APPLET_EVALUATION=${MS_APPLET_EVALUATION:-"ms_applet_evaluation:8013/applet_evaluation"}
      #- MS_AREA_EVALUATION=${MS_AREA_EVALUATION:-"ms_area_evaluation:8014/area_evaluation"}
      #- MS_AUDIO_EVALUATION=${MS_AUDIO_EVALUATION:-"ms_audio_evaluation:8015/audio_evaluation"}
      #- MS_BUTTON_EVALUATION=${MS_BUTTON_EVALUATION:-"ms_button_evaluation:8016/button_evaluation"}
      #- MS_DD_EVALUATION=${MS_DD_EVALUATION:-"ms_dd_evaluation:8018/dd_evaluation"}
      #- MS_DIV_EVALUATION=${MS_DIV_EVALUATION:-"ms_div_evaluation:8019/div_evaluation"}
      #- MS_EMBED_EVALUATION=${MS_EMBED_EVALUATION:-"ms_embed_evaluation:8020/embed_evaluation"}
      #- MS_FIELDSET_EVALUATION=${MS_FIELDSET_EVALUATION:-"ms_fieldset_evaluation:8021/fieldset_evaluation"}
      #- MS_FIGURE_EVALUATION=${MS_FIGURE_EVALUATION:-"ms_figure_evaluation:8023/figure_evaluation"}
      #- MS_HEADINGS_EVALUATION=${MS_HEADINGS_EVALUATION:-"ms_headings_evaluation:8024/headings_evaluation"}
      #- MS_IFRAME_EVALUATION=${MS_IFRAME_EVALUATION:-"ms_iframe_evaluation:8025/iframe_evaluation"}
      - MS_IMG_EVALUATION=${MS_IMG_EVALUATION:-"ms_img_evaluation:8026/img_evaluation"}
      #- MS_INPUT_EVALUATION=${MS_INPUT_EVALUATION:-"ms_input_evaluation:8027/input_evaluation"}
      #- MS_LABEL_EVALUATION=${MS_LABEL_EVALUATION:-"ms_label_evaluation:8028/label_evaluation"}
      #- MS_LEGEND_EVALUATION=${MS_LEGEND_EVALUATION:-"ms_legend_evaluation:8029/legend_evaluation"}
      #- MS_LINK_EVALUATION=${MS_LINK_EVALUATION:-"ms_link_evaluation:8030/link_evaluation"}
      #- MS_MAP_EVALUATION=${MS_MAP_EVALUATION:-"ms_map_evaluation:8031/map_evaluation"}
      #- MS_OBJECT_EVALUATION=${MS_OBJECT_EVALUATION:-"ms_object_evaluation:8032/object_evaluation"}
      #- MS_PRE_EVALUATION=${MS_PRE_EVALUATION:-"ms_pre_evaluation:8033/pre_evaluation"}
      #- MS_SPAN_EVALUATION=${MS_SPAN_EVALUATION:-"ms_span_evaluation:8034/span_evaluation"}
      #- MS_TABLE_EVALUATION=${MS_TABLE_EVALUATION:-"ms_table_evaluation:8035/table_evaluation"}
      #- MS_VIDEO_EVALUATION=${MS_VIDEO_EVALUATION:-"ms_video_evaluation:8036/video_evaluation"}
      - MS_HTML_EXTRACTION=${MS_HTML_EXTRACTION:-"ms_html_extraction:8001/html_extraction"}
      - MS_HTML_CLEANING=${MS_HTML_CLEANING:-"ms_html_cleaning:8002/html_cleaning"}
      - CS_RECOMENDATION=${CS_RECOMENDATION:-"recomendation_service:9000"}

  #ms_a_recomendation:
    #container_name: ms_a_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_a_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9010:9010

  #ms_abbr_recomendation:
    #container_name: ms_abbr_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_abbr_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9011:9011

  #ms_acronym_recomendation:
    #container_name: ms_acronym_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_acronym_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9012:9012

  #ms_applet_recomendation:
    #container_name: ms_applet_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_applet_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9013:9013

  #ms_area_recomendation:
    #container_name: ms_area_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_area_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9014:9014

  #ms_audio_recomendation:
    #container_name: ms_audio_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_audio_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9015:9015

  #ms_button_recomendation:
    #container_name: ms_button_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_button_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9016:9016

  #ms_dd_recomendation:
    #container_name: ms_dd_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_dd_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9018:9018

  #ms_div_recomendation:
    #container_name: ms_div_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_div_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9019:9019

  #ms_embed_recomendation:
    #container_name: ms_embed_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_embed_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9020:9020

  #ms_headings_recomendation:
    #container_name: ms_headings_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_headings_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9024:9024

  ms_img_recomendation:
    container_name: ms_img_recomendation
    image: mss_recomendations
    entrypoint: python3 ./MS_img_recomendation/main.py
    networks:
      - net_compatibily_service
    ports:
      - 9026:9026

  #ms_input_recomendation:
    #container_name: ms_input_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_input_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9027:9027

  #ms_label_recomendation:
    #container_name: ms_label_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_label_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9028:9028

  #ms_link_recomendation:
    #container_name: ms_link_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_link_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9030:9030

  #ms_object_recomendation:
    #container_name: ms_object_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_object_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9032:9032

  #ms_pre_recomendation:
    #container_name: ms_pre_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_pre_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9033:9033

  #ms_span_recomendation:
    #container_name: ms_span_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_span_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9034:9034

  #ms_table_recomendation:
    #container_name: ms_table_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_table_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9035:9035

  #ms_video_recomendation:
    #container_name: ms_video_recomendation
    #image: mss_recomendations
    #entrypoint: python3 ./MS_video_recomendation/main.py
    #networks:
    #  - net_compatibily_service
    #ports:
    #  - 9036:9036

  recomendation_service:
    container_name: recomendation_service
    build: ./CS_Recomendation/Recomendation_Service
    image: recomendation_service
    networks:
      - net_compatibily_service
    ports:
      - 9000:9000
    links: 
      #- ms_a_recomendation
      #- ms_abbr_recomendation
      #- ms_acronym_recomendation
      #- ms_applet_recomendation
      #- ms_area_recomendation
      #- ms_audio_recomendation
      #- ms_button_recomendation
      #- ms_dd_recomendation
      #- ms_div_recomendation
      #- ms_embed_recomendation
      #- ms_headings_recomendation
      - ms_img_recomendation
      #- ms_input_recomendation
      #- ms_label_recomendation
      #- ms_link_recomendation
      #- ms_object_recomendation
      #- ms_pre_recomendation
      #- ms_span_recomendation
      #- ms_table_recomendation
      #- ms_video_recomendation

    environment:
      #- MS_A_RECOMENDATION=${MS_A_RECOMENDATION:-"ms_a_recomendation:9010/a_recomendation"}
      #- MS_ABBR_RECOMENDATION=${MS_ABBR_RECOMENDATION:-"ms_abbr_recomendation:9011/abbr_recomendation"}
      #- MS_ACRONYM_RECOMENDATION=${MS_ACRONYM_RECOMENDATION:-"ms_acronym_recomendation:9012/acronym_recomendation"}
      #- MS_APPLET_RECOMENDATION=${MS_APPLET_RECOMENDATION:-"ms_applet_recomendation:9013/applet_recomendation"}
      #- MS_AREA_RECOMENDATION=${MS_AREA_RECOMENDATION:-"ms_area_recomendation:9014/area_recomendation"}
      #- MS_AUDIO_RECOMENDATION=${MS_AUDIO_RECOMENDATION:-"ms_audio_recomendation:9015/audio_recomendation"}
      #- MS_BUTTON_RECOMENDATION=${MS_BUTTON_RECOMENDATION:-"ms_button_recomendation:9016/button_recomendation"}
      #- MS_DD_RECOMENDATION=${MS_DD_RECOMENDATION:-"ms_dd_recomendation:9018/dd_recomendation"}
      #- MS_DIV_RECOMENDATION=${MS_DIV_RECOMENDATION:-"ms_div_recomendation:9019/div_recomendation"}
      #- MS_EMBED_RECOMENDATION=${MS_EMBED_RECOMENDATION:-"ms_embed_recomendation:9020/embed_recomendation"}
      #- MS_HEADINGS_RECOMENDATION=${MS_HEADINGS_RECOMENDATION:-"ms_headings_recomendation:9024/headings_recomendation"}
      - MS_IMG_RECOMENDATION=${MS_IMG_RECOMENDATION:-"ms_img_recomendation:9026/img_recomendation"}
      #- MS_INPUT_RECOMENDATION=${MS_INPUT_RECOMENDATION:-"ms_input_recomendation:9027/input_recomendation"}
      #- MS_LABEL_RECOMENDATION=${MS_LABEL_RECOMENDATION:-"ms_label_recomendation:9028/label_recomendation"}
      #- MS_LINK_RECOMENDATION=${MS_LINK_RECOMENDATION:-"ms_link_recomendation:9030/link_recomendation"}
      #- MS_OBJECT_RECOMENDATION=${MS_OBJECT_RECOMENDATION:-"ms_object_recomendation:9032/object_recomendation"}
      #- MS_PRE_RECOMENDATION=${MS_PRE_RECOMENDATION:-"ms_pre_recomendation:9033/pre_recomendation"}
      #- MS_SPAN_RECOMENDATION=${MS_SPAN_RECOMENDATION:-"ms_span_recomendation:9034/span_recomendation"}
      #- MS_TABLE_RECOMENDATION=${MS_TABLE_RECOMENDATION:-"ms_table_recomendation:9035/table_recomendation"}
      #- MS_VIDEO_RECOMENDATION=${MS_VIDEO_RECOMENDATION:-"ms_video_recomendation:9036/video_recomendation"}
      - MS_HTML_EXTRACTION=${MS_HTML_EXTRACTION:-"ms_html_extraction:8001/html_extraction"}
      - MS_HTML_CLEANING=${MS_HTML_CLEANING:-"ms_html_cleaning:8002/html_cleaning"}
      - CS_EVALUATION=${CS_EVALUATION:-"evaluation_service:8000"}

networks:                           #creación de la red 
  net_compatibily_service:          #"variable" para indicar la red a utilizar
    name: compatibility_service     #nombre de la red, se pueden ver sus especificaciones ejecutando en consola: "docker network inspect <nombre de la red>"